[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Econometrics = "4d6a76a9-bfbc-5492-8924-cf6ed7875f06"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
